language: csharp
solution: src/Epicoin/Epicoin.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
  - nuget restore src/Epicoin/Epicoin.sln
script:    
  - git pull
  - git fetch --all
  - echo "Master Test"
  - git checkout master && git pull origin master
  - make build
  - echo "Develop Test"
  - git checkout develop && git pull origin develop
  - make build

